version: '3.7'

networks:
    default:
         name: NETWORKNAME
         external: true

services:
    WatchListBackend:
        container_name: WatchListBackend
        stdin_open: true
        tty: true
        image: watchlistbackend:latest
        hostname: WatchListBackend
        environment:
               - AUTH_KEY=YOUR_AUTH_KEY
               - WatchList_User=DB_USERNAME
               - WatchList_Password=DB_PASSWORD
               - WatchList_Host=DB_HOST
               - WatchList_DB=DB_NAME
        networks:
            - default
        restart: always
