swagger: '2.0'
info:
  description: "WatchList backend"
  version: 3.0.0
  title: WatchList swagger backend
tags:
  - name: WatchList
    description: WatchList swagger backend
schemes:
  - https
  - http
servers:
  - url: http://localhost:8080
    description: Localhost
paths:
  /AddWatchList:
    put:
      tags:
        - WatchList
      summary: Add WatchList record
      description: 'Add WatchList record'
      #consumes:
      #  - application/json
      #produces:
      #  - application/json WatchListItemID
      parameters:
        - in: query
          name: WatchListItemID
          type: integer
          required: true
        - in: query
          name: StartDate
          type: string
          required: true
        - in: query
          name: EndDate
          type: string
          required: false
        - in: query
          name: WatchListSourceID
          type: integer
          required: false
        - in: query
          name: Season
          type: integer
          required: false
        - in: query
          name: Notes
          type: string
          required: false
      responses:
        '200':
          description: "['OK',''] on success, ['ERROR','ERROR MESSAGE'] on error"
  /AddWatchListItem:
    put:
      tags:
        - WatchListItem
      summary: Add WatchList item
      description: 'Add WatchList item which is a movie, tv show or special'
      parameters:
        - in: query
          name: Name
          type: string
          required: true
        - in: query
          name: WatchListTypeID
          type: integer
          required: true
        - in: query
          name: IMDB_URL
          type: string
          required: false
        - in: query
          name: Notes
          type: string
          required: false
      responses:
        '200':
          description: "['OK',''] on success, ['ERROR','ERROR MESSAGE'] on error"
  /AddWatchListQueueItem:
    put:
      tags:
        - WatchListQueueItem
      summary: Add WatchList queue item
      description: 'Add WatchList queue item'
      parameters:
        - in: query
          name: WatchListItemID
          type: integer
          required: true
        - in: query
          name: Notes
          type: string
          required: false
      responses:
        '200':
          description: "['OK',''] on success, ['ERROR','ERROR MESSAGE'] on error"
  /DeleteWatchList:
    put:
      tags:
        - WatchList
      summary: Delete WatchList record
      description: 'Delete WatchList record'
      parameters:
        - in: query
          name: WatchListID
          type: integer
          required: true
      responses:
        '200':
          description: "['OK',''] on success, ['ERROR','ERROR MESSAGE'] on error"
  /DeleteWatchListItem:
    put:
      tags:
        - WatchListItem
      summary: Delete WatchList Item record
      description: 'Delete WatchList Item record'
      parameters:
        - in: query
          name: WatchListItemID
          type: integer
          required: true
      responses:
        '200':
          description: "['OK',''] on success, ['ERROR','ERROR MESSAGE'] on error"
  /DeleteWatchListQueueItem:
    put:
      tags:
        - WatchListQueueItem
      summary: Delete WatchList QueueItem record
      description: 'Delete WatchList Queue Item record'
      parameters:
        - in: query
          name: WatchListQueueItemID
          type: integer
          required: true
      responses:
        '200':
          description: "['OK',''] on success, ['ERROR','ERROR MESSAGE'] on error"
  /GetWatchList:
    get:
      tags:
        - WatchList
      summary: Get WatchList records
      description: 'Get WatchList records'
      parameters:
        - in: query
          name: IncompleteFilter
          type: string
          required: false
        - in: query
          name: RecordLimit
          type: string
          required: false
        - in: query
          name: SearchTerm
          type: string
          required: false
        - in: query
          name: SortColumn
          type: string
          required: false
        - in: query
          name: SortDirection
          type: string
          required: false
        - in: query
          name: SourceFilter
          type: string
          required: false
      responses:
        '200':
          description: "WatchList records on success, ['ERROR','ERROR MESSAGE'] on error"
  /GetWatchListItems:
    put:
      tags:
        - WatchListItems
      summary: Get WatchList item records
      description: 'Get WatchList item records'
      parameters:
        - in: query
          name: IMDBURLMissing
          type: string
          required: false
        - in: query
          name: RecordLimit
          type: string
          required: false
        - in: query
          name: SearchTerm
          type: string
          required: false
        - in: query
          name: SortColumn
          type: string
          required: false
        - in: query
          name: SortDirection
          type: string
          required: false
      responses:
        '200':
          description: "WatchList records on success, ['ERROR','ERROR MESSAGE'] on error"
  /GetWatchListQueue:
    put:
      tags:
        - WatchListQueue
      summary: Get WatchList queue records
      description: 'Get WatchList queue records'
      parameters:
        - in: query
          name: SearchTerm
          type: string
          required: false
      responses:
        '200':
          description: "WatchList queue records on success, ['ERROR','ERROR MESSAGE'] on error"
  /GetWatchListSources:
    put:
      tags:
        - WatchListSources
      summary: Get WatchList Sources
      description: 'Get WatchList Sources'
      responses:
        '200':
          description: "WatchList source records on success, ['ERROR','ERROR MESSAGE'] on error"
  /GetWatchListTypes:
    put:
      tags:
        - WatchListTypes
      summary: Get WatchList Types
      description: 'Get WatchList Types'
      responses:
        '200':
          description: "WatchList types records on success, ['ERROR','ERROR MESSAGE'] on error"
  /GetWatchListTVStats:
    put:
      summary: Get WatchList Movie Stats
      description: 'Get WatchList Movie Stats'
      tags:
           - Misc
      responses:
        '200':
          description: "WatchList movie stats on success, ['ERROR','ERROR MESSAGE'] on error"
  /IsIMDBSearchEnabled:
    put:
      summary: Returns flag to indicate if RapidAPI IMDB API key is defined
      description: 'Returns flag to indicate if RapidAPI IMDB API key is defined'
      tags:
           - Misc
      responses:
        '200':
          description: "true or false"
  /SearchIMDB:
    get:
      summary: Search for a movie or TV show on IMDB
      description: 'Search for a movie or TV show on IMDB'
      tags:
           - Misc
      parameters:
        - in: query
          name: SearchTerm
          type: string
          required: true
      responses:
        '200':
          description: "IMDB search results or error mesage on error"
  /UpdateWatchList:
    put:
      tags:
        - WatchList
      summary: Add WatchList record
      description: 'Update WatchList record'
      #consumes:
      #  - application/json
      #produces:
      #  - application/json WatchListItemID
      parameters:
        - in: query
          name: WatchListID
          type: integer
          required: true
        - in: query
          name: WatchListItemID
          type: integer
          required: true
        - in: query
          name: StartDate
          type: string
          required: true
        - in: query
          name: EndDate
          type: string
          required: false
        - in: query
          name: WatchListSourceID
          type: integer
          required: false
        - in: query
          name: Season
          type: integer
          required: false
        - in: query
          name: Notes
          type: string
          required: false
      responses:
        '200':
          description: "['OK',''] on success, ['ERROR','ERROR MESSAGE'] on error"



  /UpdateWatchListItem:
    put:
      tags:
        - WatchListItem
      summary: Update WatchList item
      description: 'Update WatchList item'
      parameters:
        - in: query
          name: WatchListItemID
          type: integer
          required: true
        - in: query
          name: Name
          type: string
          required: true
        - in: query
          name: WatchListTypeID
          type: integer
          required: true
        - in: query
          name: IMDB_URL
          type: string
          required: false
        - in: query
          name: Notes
          type: string
          required: false
      responses:
        '200':
          description: "['OK',''] on success, ['ERROR','ERROR MESSAGE'] on error"
  /UpdateWatchListQueueItem:
    put:
      tags:
        - WatchListQueueItem
      summary: Update WatchList queue item
      description: 'Update WatchList queue item'
      parameters:
        - in: query
          name: WatchListQueueItemID
          type: integer
          required: true
        - in: query
          name: WatchListItemID
          type: integer
          required: false
        - in: query
          name: Notes
          type: string
          required: false
      responses:
        '200':
          description: "['OK',''] on success, ['ERROR','ERROR MESSAGE'] on error"
#securityDefinitions:
#  petstore_auth:
#    type: oauth2
#    authorizationUrl: http://petstore.swagger.io/oauth/dialog
#    flow: implicit
#    scopes:
#      write:pets: modify pets in your account
#      read:pets: read your pets
#  api_key:
#    type: apiKey
#    name: api_key
#    in: header
definitions:
  WatchList:
    properties:
      WatchListID:
        type: integer
      WatchListItemID:
        type: integer
      StartDate:
        type: string
        format: date
      EndDate:
        type: string
        format: date
      WatchListSourceID:
        type: integer
        #description: Order Status
        #enum:
        #  - placed
        #  - approved
        #  - delivered
      Season:
        type: integer
      Notes:
           type: string
  WatchListItems:
    properties:
      WatchListItemID:
        type: integer
      WatchListItemName:
        type: string
      WatchListTypeID:
        type: integer
      IMDB_URL:
        type: string
      ItemNotes:
        type: string
  WatchListQueueItems:
    properties:
      WatchListQueueItemID:
        type: integer
      WatchListItemID:
        type: integer
      Notes:
        type: string
  WatchListSources:
    properties:
      WatchListSourceID:
        type: integer
      WatchListSourceName:
        type: string
  WatchListTypes:
    properties:
      WatchListTypeID:
        type: integer
      WatchListTypeName:
        type: string